### ISSUE TITLE
Save and load state

### ISSUE THREAD

**Issue by brenns10** [cwruacm/lulu#14]
This is more a thought for a future feature, when there is time for more exciting development.

Hubot looses the associations (e.g. siretrm is a despot) and the karma when it restarts.  Maybe we can find a way to save hubot's state and load it again, so that we don't lose these (airquotes) "gems".

**Comment by thomasrussellmurphy** [comment]
Implementation through local redis server: https://www.npmjs.com/package/hubot-redis-brain

**Comment by brenns10** [comment]
We did it!
