### ISSUE TITLE
Doesn't make me sandwiches

### ISSUE THREAD

**Issue by raidancampbell** [cwruacm/lulu#16]
Expected behavior:
    When I say "lulu makemeasandwich", a delicious sandwich appears before me within a reasonable amount of time

Actual behavior:
    When I say "lulu makemeasandwich", I remain sandwichless, starving in Glennan.

Possible fix:
     add https://www.npmjs.com/package/makemeasandwich to lulu's source

**Comment by brenns10** [comment]
This might be too easily to accidentally/intentionally abuse in IRC.  (@thomasrussellmurphy - back me up or overrule me here).  I'd recommend the following workaround:

``` bash
npm install -g makemeasandwich
makemeasandwich
```

Which you can type into your terminal, instead of IRC.

**Comment by thomasrussellmurphy** [comment]
I'm not putting payment processing on IRC. Noooooppeeeee.

**Comment by brenns10** [comment]
Then we close.
