### ISSUE TITLE
incomplete help text

### ISSUE THREAD

**Issue by raidancampbell** [cwruacm/lulu#17]
doing a query against lulu with "lulu help", or, more preferably "/msg lulu help", produces an instant flood of returned text.

lulu is likely hitting the IRC's preconfigured flood limit, and being cut off.

This could also explain why lulu sometimes doesn't provide URL about text for links sometimes.

**Comment by brenns10** [comment]
As I understand it, IRC admins (read: yetanothername) have set special flood limits for lulu in some of the main channels.  And the server probably has its own flood limit.  Lulu has way too many commands to efficiently list, so maybe we should just make a list here and have lulu send a link.
