### ISSUE TITLE
Implementation of fuck.coffee does not count emphatic letter repetition

### ISSUE THREAD

**Issue by thomasrussellmurphy** [cwruacm/lulu#28]
A friend of mine noted that fuck.coffee does not recognize emphatic letter repetition when detecting its namesake profanity. @brenns10, would it be reasonable to change to recognize repeated letter(s) in the regex? Location for change would be: https://github.com/cwruacm/lulu/blob/25fa1ac03cd625e8402c9814d431ae6b6d166933/scripts/fuck.coffee#L14

**Comment by brenns10** [comment]
How about #29?

**Comment by brenns10** [comment]
D-D-D-DONE!
